### ISSUE TITLE
Shoutem cli install error

### ISSUE THREAD

**Issue by mikev10** [shoutem/ui#305]
I am trying to follow the steps listed [here](https://shoutem.github.io/docs/extensions/tutorials/getting-started) but keep getting an error when trying to install `shoutem-cli - $ npm install -g @shoutem/cli`

```
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ngrok@2.2.21 postinstall: `node ./postinstall.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ngrok@2.2.21 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional log                                     ging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2017-08-24T13_20_31_973Z-debug.log
```

The log file can be found [here](https://gist.github.com/mikev10/9589151299ead7b85afed0117df27e7c).

I'm not sure where to begin so any help would be greatly appreciated.

Thanks!

**Comment by Vladimir-Vdovic** [comment]
This isn't the appropriate repository for CLI errors. Please report these @shoutem/cli issues in it's respective [repository](https://github.com/shoutem/cli/issues).

Note: I believe this issue has been resolved now, as we've answered on the [Stack Overflow](https://stackoverflow.com/questions/45868359/shoutem-install-error/45870113#45870113) question you posted as well.

Closing issue: Resolved and wrong repository.

**Comment by mikev10** [comment]
I will move it over to the correct repository as this issue is still not resolved. That answer did not work.
